# Generated by Django 5.0 on 2024-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
